=== TheOutsiderMan/task-3-3-rabets/src/main/resources/schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.epam-training.by" xmlns="http://www.epam-training.by">
  <xs:element name="movies" type="moviesType"/>
  <xs:complexType name="titleType">
    <xs:sequence>
      <xs:element type="xs:string" name="russian"/>
      <xs:element type="xs:string" name="original"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="movieType">
    <xs:sequence>
      <xs:element type="titleType" name="title"/>
      <xs:element type="xs:int" name="year"/>
      <xs:element type="xs:string" name="country"/>
      <xs:element type="xs:string" name="director"/>
      <xs:element type="xs:string" name="actor"/>
      <xs:element type="xs:string" name="genre"/>
      <xs:element type="xs:string" name="imdb-rating"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="moviesType">
    <xs:sequence>
      <xs:element type="movieType" name="movie" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== TheOutsiderMan/task-3-3-rabets/src/main/resources/source.xml
<?xml version="1.0" encoding="UTF-8" ?>
<movies xmlns="http://www.epam-training.by" xsi:schemaLocation="http://www.epam-training.by schema.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <movie>
      <title>
         <russian>Истории семьи Майровиц</russian>
         <original>The Meyerowitz Stories (New and Selected)</original>
      </title>
      <year>2017</year>
      <country>США</country>
      <director>Ноа Баумбак</director>
      <actor>Адам Сэндлер, Грэйс Ван Паттен, Дастин Хоффман</actor>
      <genre>драма, комедия</genre>
      <imdb-rating>7,1</imdb-rating>
   </movie>
   <movie>
      <title>
         <russian>Окча</russian>
         <original>Okja</original>
      </title>
      <year>2017</year>
      <country>Корея Южная, США</country>
      <director>Пон Джун-хо</director>
      <actor>Ан Со-хён, Тильда Суинтон, Джейк Джилленхол</actor>
      <genre>фантастика, боевик, драма</genre>
      <imdb-rating>7.4</imdb-rating>
   </movie>
   <movie>
      <title>
         <russian>Хорошее время</russian>
         <original>Good Time</original>
      </title>
      <year>2017</year>
      <country>США</country>
      <director>Бен Сэфди, Джошуа Сэфди</director>
      <actor>Роберт Паттинсон, Бен Сэфди, Taliah Webster</actor>
      <genre>триллер, драма, криминал</genre>
      <imdb-rating>7,5</imdb-rating>
   </movie>
   <movie>
      <title>
         <russian>Квадрат</russian>
         <original>The Square</original>
      </title>
      <year>2017</year>
      <country>Швеция, Германия, Франция</country>
      <director>Рубен Эстлунд</director>
      <actor>Клас Банг, Элизабет Мосс, Доминик Уэст</actor>
      <genre>драма, комедия</genre>
      <imdb-rating>7,7</imdb-rating>
   </movie>
   <movie>
      <title>
         <russian>Мир, полный чудес</russian>
         <original>Wonderstruck</original>
      </title>
      <year>2017</year>
      <country>США</country>
      <director>Тодд Хейнс</director>
      <actor>Милли Симмондс, Джулианна Мур, Кори Майкл Смит</actor>
      <genre>драма, детектив, семейный</genre>
      <imdb-rating>6,9</imdb-rating>
   </movie>
   <movie>
      <title>
         <russian>Тебя никогда здесь не было</russian>
         <original>You Were Never Really Here</original>
      </title>
      <year>2017</year>
      <country>Великобритания, Франция, США</country>
      <director>Линн Рэмси</director>
      <actor>Хоакин Феникс, Екатерина Самсонов, Алессандро Нивола</actor>
      <genre>триллер, драма, детектив</genre>
      <imdb-rating>7,5</imdb-rating>
   </movie>
   <movie>
      <title>
         <russian>Хорошего дня</russian>
         <original>Hao ji le</original>
      </title>
      <year>2017</year>
      <country>Китай</country>
      <director>Лю Цзянь</director>
      <actor>Хоакин Феникс, Екатерина Самсонов, Алессандро Нивола</actor>
      <genre>мультфильм, комедия, криминал</genre>
      <imdb-rating>6,9</imdb-rating>
   </movie>
   <movie>
      <title>
         <russian>Ана, любовь моя</russian>
         <original>Ana, mon amour</original>
      </title>
      <year>2017</year>
      <country>Румыния, Германия, Франция</country>
      <director>Калин Питер Нецер</director>
      <actor>Диана Каваллиоти, Mircea Postelnicu, Кармен Тэнасе</actor>
      <genre>драма</genre>
      <imdb-rating>7,3</imdb-rating>
   </movie>
   <movie>
      <title>
         <russian>Реквием по госпоже Ю.</russian>
         <original>Rekvijem za gospodju J</original>
      </title>
      <year>2017</year>
      <country>Сербия, Болгария, Македония</country>
      <director>Боян Вулетич</director>
      <actor>Миряна Каранович, Йована Гаврилович, Даника Неделькович</actor>
      <genre>комедия</genre>
      <imdb-rating>7,4</imdb-rating>
   </movie>
   <movie>
      <title>
         <russian>Дикая история</russian>
         <original>El bar</original>
      </title>
      <year>2016</year>
      <country>Испания, Аргентина</country>
      <director>Алекс де ла Иглесиа</director>
      <actor>Бланка Суарес, Марио Касас, Кармен Мачи</actor>
      <genre>ужасы, триллер, комедия</genre>
      <imdb-rating>6,4</imdb-rating>
   </movie>
   <movie>
      <title>
         <russian>Затерянный город Z</russian>
         <original>The Lost City of Z</original>
      </title>
      <year>2016</year>
      <country>США</country>
      <director>Джеймс Грэй</director>
      <actor>Чарли Ханнэм, Роберт Паттинсон, Сиенна Миллер</actor>
      <genre>драма, приключения, биография</genre>
      <imdb-rating>6,6</imdb-rating>
   </movie>
   <movie>
      <title>
         <russian>Зови меня своим именем</russian>
         <original>Call Me by Your Name</original>
      </title>
      <year>2017</year>
      <country>Италия, Франция, Бразилия</country>
      <director>Лука Гуаданьино</director>
      <actor>Арми Хаммер, Тимоти Шаламе, Майкл Стулбарг</actor>
      <genre>драма, мелодрама</genre>
      <imdb-rating>8,4</imdb-rating>
   </movie>
   <movie>
      <title>
         <russian>Заложники</russian>
         <original />
      </title>
      <year>2017</year>
      <country>Россия, Грузия</country>
      <director>Резо Гигинеишвили</director>
      <actor>Иракли Квирикадзе, Тинатин Далакишвили</actor>
      <genre>драма, триллер, биография</genre>
      <imdb-rating>6,6</imdb-rating>
   </movie>
   <movie>
      <title>
         <russian>Фелисите</russian>
         <original>Felicite</original>
      </title>
      <year>2017</year>
      <country>Франция, Германия, Бельгия</country>
      <director>Ален Гомис</director>
      <actor>V?ro Tshanda Beya Mputu, Gaetan Claudia, Papi Mpaka</actor>
      <genre>драма, музыка</genre>
      <imdb-rating>6,6</imdb-rating>
   </movie>
   <movie>
      <title>
         <russian>Фантастическая женщина</russian>
         <original>Una Mujer Fantastica</original>
      </title>
      <year>2017</year>
      <country>Чили, Германия, Испания</country>
      <director>Себастьян Лелио</director>
      <actor>Daniela Vega, Франсиско Рейес, Луис Ньекко</actor>
      <genre>драма</genre>
      <imdb-rating>7,5</imdb-rating>
   </movie>
   <movie>
      <title>
         <russian>По ту сторону надежды</russian>
         <original>Toivon tuolla puolen</original>
      </title>
      <year>2017</year>
      <country>Финляндия, Германия</country>
      <director>Аки Каурисмяки</director>
      <actor>Вилле Виртанен, Кати Оутинен, Доме Карукоски</actor>
      <genre>драма, комедия</genre>
      <imdb-rating>7,3</imdb-rating>
   </movie>
   <movie>
      <title>
         <russian>О теле и душе</russian>
         <original>Testr?l es Lelekr?l</original>
      </title>
      <year>2017</year>
      <country>Венгрия</country>
      <director>Ильдико Эньеди</director>
      <actor>Геза Морчани, Александра Борбей, Золтан Шнайдер</actor>
      <genre>драма, мелодрама</genre>
      <imdb-rating>8,1</imdb-rating>
   </movie>
   <movie>
      <title>
         <russian>Аустерлиц</russian>
         <original>Austerlitz</original>
      </title>
      <year>2016</year>
      <country>Германия</country>
      <director>Сергей Лозница</director>
      <actor>Геза Морчани, Александра Борбей, Золтан Шнайдер</actor>
      <genre>документальный</genre>
      <imdb-rating>6,6</imdb-rating>
   </movie>
   <movie>
      <title>
         <russian>Кроткая</russian>
         <original />
      </title>
      <year>2017</year>
      <country>Франция, Россия, Германия</country>
      <director>Сергей Лозница</director>
      <actor>Василина Маковцева, Валериу Андрюцэ, Сергей Колесов</actor>
      <genre>драма, детектив</genre>
      <imdb-rating>7,1</imdb-rating>
   </movie>
   <movie>
      <title>
         <russian>Перестрелка</russian>
         <original>Free Fire</original>
      </title>
      <year>2016</year>
      <country>Великобритания, Франция</country>
      <director>Бен Уитли</director>
      <actor>Энцо Чиленти, Сэм Райли, Майкл Смайли</actor>
      <genre>боевик, триллер, комедия</genre>
      <imdb-rating>6,5</imdb-rating>
   </movie>
   <movie>
      <title>
         <russian>Песня за песней</russian>
         <original>Song to Song</original>
      </title>
      <year>2015</year>
      <country>США</country>
      <director>Терренс Малик</director>
      <actor>Натали Портман, Майкл Фассбендер, Райан Гослинг</actor>
      <genre>драма, мелодрама, музыка</genre>
      <imdb-rating>5,8</imdb-rating>
   </movie>
   <movie>
      <title>
         <russian>Прочь</russian>
         <original>Get Out</original>
      </title>
      <year>2017</year>
      <country>США</country>
      <director>Джордан Пил</director>
      <actor>Дэниэл Калуя, Эллисон Уильямс, Кэтрин Кинер</actor>
      <genre>ужасы, детектив, триллер</genre>
      <imdb-rating>7,7</imdb-rating>
   </movie>
   <movie>
      <title>
         <russian>Рыжий пес: Самый верный</russian>
         <original>Red Dog: True Blue</original>
      </title>
      <year>2016</year>
      <country>Австралия</country>
      <director>Крив Стендерс</director>
      <actor>Джейсон Айзекс, Леви Миллер, Брайан Браун</actor>
      <genre>драма, мелодрама, комедия</genre>
      <imdb-rating>6,5</imdb-rating>
   </movie>
   <movie>
      <title>
         <russian>В лучах солнца</russian>
         <original />
      </title>
      <year>2015</year>
      <country>Чехия, Россия, Германия</country>
      <director>Виталий Манский</director>
      <actor>Ли Джин-ми, Ю-ён, Хе-ён</actor>
      <genre>документальный</genre>
      <imdb-rating>7,4</imdb-rating>
   </movie>
   <movie>
      <title>
         <russian>Костер на ветру</russian>
         <original />
      </title>
      <year>2016</year>
      <country>Россия</country>
